# 范例

<br>

下面的例子中，我以一个`ResourcePool`对象管理一些创建代价高昂而又可以重复使用的资源(例如数据库连接)。

这个对象带有两个“池” `(pool)`：一个用以保存可用资源，一个用以保存已分配资源。

当用户请求一份资源时，`ResourcePool`对象从“可用资源池”中取出一份资源交出，并将这份资源转移到“已分配资源池”。

当用户释放一份资源时，`ResourcePool`对象就将该资源从“已分配资源池”放回“可用资源池”。

如果“可用资源池”不能满足用户的请求，`ResourcePool`对象就创建一份新资源。

<br>

资源供应函数可能如下所示：

```java
class ResourcePool {
    Resource getResource() {
        Resource result;
        try {
            result = (Resource) _available.pop();
            _allocated.push(result);
            return result;
        } catch (EmptyStackException e) {
            result = new Resource();
            _allocated.push(result);
            return result;
        }
    }
    Stack _available;
    Stack _allocated;
}
```

在这里，“可用资源用尽”并不是一种意料外的事件，因此我不该使用异常表示这种情况。

<br>

为了去掉这里的异常，我首先必须添加一个适当的提前测试，并在其中处理“可用资源池为空”的情况：

```diff
    Resource getResource() {
        Resource result;
+        if (_available.isEmpty()) {
+            result = new Resource();
+            _allocated.push(result);
+            return result;
        } 
        else {
            try {
                result = (Resource) _available.pop();
                _allocated.push(result);
                return result;
            } catch (EmptyStackException e) {
                result = new Resource();
                _allocated.push(result);
                return result;
            }
        }
    }
```



现在`getResource()`应该绝对不会抛出异常了。

我可以添加断言保证这一点：

```diff
    Resource getResource() {
        Resource result;
        if (_available.isEmpty()) {
            result = new Resource();
            _allocated.push(result);
            return result;
        } else {
            try {
                result = (Resource) _available.pop();
                _allocated.push(result);
                return result;
            } catch (EmptyStackException e) {
+                Assert.shouldNeverReachHere("available was empty on pop");
                result = new Resource();
                _allocated.push(result);
                return result;
            }
        }
    }
    
class Assert...
    static void shouldNeverReachHere(String message) {
        throw new RuntimeException(message);
    }
```

编译并测试。

如果一切运转正常，就可以将`try`区段中的代码复制到`try`区段之外，然后将`try`区段全部移除：

```java
    Resource getResource() {
        Resource result;
        if (_available.isEmpty()) {
            result = new Resource();
            _allocated.push(result);
            return result;
        } else {
            result = (Resource) _available.pop();
            _allocated.push(result);
            return result;
        }
    }
```

在这之后我常常发现，可以对条件代码加以整理。

本例之中我可以使用`Consolidate Duplicate Conditional Fragments (243)`:

```java
    Resource getResource() {
        Resource result;
        if (_available.isEmpty())
            result = new Resource();
        else
            result = (Resource) _available.pop();
        _allocated.push(result);
        return result;
    }
```



<br>

